name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:   # <-- ADD THIS BLOCK
  column_alias_map:
    dm_site:
      code: "Site Code"
      psite_initial: "Parent Site Initial"
      name: "Site Name"
      reportname: "Report Name"
      sitetype: "Site Type"
      installation_type: "Installation Type"
      ctname: "City Code"
      store_size: "Store Size"
      store_startdt: "Store Start Date"
      store_closedt: "Store Closed Date"
      rph1: "Phone Number"
      fax: "Fax Number"
      udfstring01: "Business Type"
      udfstring04: "Site Category"
      udfstring10: "Format Type"
      udfstring15: "Status"
      udfstring29: "Owner Name"
      udfstring31: "Manager Name"
      udfstring32: "Brand"
      udfstring33: "Cluster"
      udfstring34: "Region"
      udfstring38: "Franchise Type"
      udfstring39: "Operating Model"
      age: "Age Category"
      stname: "State Name"
      cnname: "City Name"
      zone: "Zone"
      class: "City Class"
      dataversion: "Data Version"
      upload_time: "Upload Time"

models:
  my_new_project:
    item:
      +materialized: view
      +schema: STAGING
      +database: VFLPOC
      +schema_generation: none

    site:
      +materialized: view
      +schema: STAGING
      +database: VFLPOC
      +schema_generation: none
