name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  column_alias_map:
    dm_site:
      code: "Site Code"
      psite_initial: "Parent Site Initial"
      name: "Site Name"
      reportname: "Report Name"
      sitetype: "Site Type"
      installation_type: "Installation Type"
      ctname: "City Code"
      store_size: "Store Size"
      store_startdt: "Store Start Date"
      store_closedt: "Store Closed Date"
      rph1: "Phone Number"
      fax: "Fax Number"
      udfstring01: "Business Type"
      udfstring04: "Site Category"
      udfstring10: "Format Type"
      udfstring15: "Status"
      udfstring29: "Owner Name"
      udfstring31: "Manager Name"
      udfstring32: "Brand"
      udfstring33: "Cluster"
      udfstring34: "Region"
      udfstring38: "Franchise Type"
      udfstring39: "Operating Model"
      age: "Age Category"
      stname: "State Name"
      cnname: "City Name"
      zone: "Zone"
      class: "City Class"
      dataversion: "Data Version"
      upload_time: "Upload Time"

    dm_item:
      icode: "Item Code"
      divisioncode: "Division Code"
      lev1grpname: "Level 1 Group Name"
      sectioncode: "Section Code"
      lev2grpname: "Level 2 Group Name"
      grpcode: "Group Code"
      barcode: "Barcode"
      grpname: "Group Name"
      route: "Route Name"
      routegrp: "Route Group"
      cname1: "CName 1"
      cname2: "Company Name 2"
      cname4: "Company Name 4"
      cname5: "Company Name 5"
      cname6: "Company Name 6"
      itemdesc2: "Item Description 2"
      itemdesc3: "Item Description 3"
      itemdesc4: "Item Description 4"
      itemdesc5: "Item Description 5"
      itemdesc6: "Item Description 6"
      udfstring02: "UDF String 02"
      udfstring03: "UDF String 03"
      udfstring05: "UDF String 05"
      udfstring07: "UDF String 07"
      udfstring09: "UDF String 09"
      udfstring10: "UDF String 10"
      udfstring20: "UDF String 20"
      invattr1_code: "Attribute 1 Code"
      invattr1_name: "Attribute 1 Name"
      invattr4_code: "Attribute 4 Code"
      invattr4_name: "Attribute 4 Name"
      mrp: "MRP"
      costrate: "Cost Rate"
      partyname: "Party Name"
      image_url: "Compressed Image URL"
      image_url_original: "Original Image URL"
      extinct: "Extinct Flag"
      generated: "Generated Flag"
      last_changed: "Last Changed Timestamp"


models:
  my_new_project:
    item:
      +materialized: view
      +schema: STAGING
      +database: VFLPOC
      +schema_generation: none

    site:
      +materialized: view
      +schema: STAGING
      +database: VFLPOC
      +schema_generation: none
