{{ config(materialized='view') }}

SELECT
    SITE.CODE,
    COALESCE(SITE.PSITE_INITIAL, 'NA') AS PSITE_INITIAL,
    SITE.NAME,
    COALESCE(SITE.REPORTNAME, 'NA') AS REPORTNAME,
    SITE.SITETYPE,
    SITE.INSTALLATION_TYPE,
    SITE.CTNAME,
    SITE.STORE_SIZE,
    SITE.STORE_STARTDT,
    SITE.STORE_CLOSEDT,
    SITE.RPH1,
    SITE.FAX,
    SITE.UDFSTRING01,
    SITE.UDFSTRING04,
    SITE.UDFSTRING10,
    SITE.UDFSTRING15,
    SITE.UDFSTRING29,
    SITE.UDFSTRING31,
    SITE.UDFSTRING32,
    SITE.UDFSTRING33,
    SITE.UDFSTRING34,
    SITE.UDFSTRING38,
    SITE.UDFSTRING39,

    -- AGE logic
    CASE
        WHEN SITE.STORE_CLOSEDT IS NOT NULL
             AND UPPER(COALESCE(SITE.UDFSTRING15, 'NA')) = 'CLOSED'
            THEN 'CLOSED'
        WHEN SITE.STORE_STARTDT BETWEEN DATE_FROM_PARTS(YEAR(DATEADD(MONTH, -3, CURRENT_DATE)), 4, 1)
                                   AND CURRENT_DATE
            THEN 'NEW'
        WHEN SITE.STORE_STARTDT BETWEEN DATE_FROM_PARTS(YEAR(DATEADD(MONTH, -15, CURRENT_DATE)), 4, 1)
                                   AND DATE_FROM_PARTS(YEAR(DATEADD(MONTH, -3, CURRENT_DATE)), 3, 31)
            THEN 'ANNUALISED'
        WHEN SITE.STORE_STARTDT < DATE_FROM_PARTS(YEAR(DATEADD(MONTH, -3, CURRENT_DATE)) - 1, 4, 1)
            THEN 'L2L'
        ELSE 'NA'
    END AS AGE,

    CITY.STNAME,
    CITY.CNNAME,

    -- Zone logic
    CASE
        WHEN UPPER(COALESCE(CITY.ZONE, 'NA')) = 'CENTRAL'          THEN 'WEST'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'ANDHRA PRADESH' THEN 'SOUTH 2'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'TELANGANA'      THEN 'SOUTH 2'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'KARNATAKA'      THEN 'SOUTH 1'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'KERALA'         THEN 'SOUTH 1'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'PUDUCHERRY'     THEN 'SOUTH 1'
        WHEN UPPER(COALESCE(CITY.STNAME, 'NA')) = 'TAMIL NADU'     THEN 'SOUTH 1'
        ELSE UPPER(COALESCE(CITY.ZONE, 'NA'))
    END AS ZONE,

    CITY.CLASS,
    SITE.DATAVERSION,
    CURRENT_TIMESTAMP AS UPLOAD_TIME

FROM {{ source('raw', 'admsite') }} SITE
LEFT JOIN {{ source('raw', 'admcity') }} CITY
    ON SITE.CTNAME = CITY.CTNAME
